apiVersion: apps/v1
kind: Deployment
metadata:
  name: smilehelper-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smilehelper-app
  template:
    metadata:
      labels:
        app: smilehelper-app
    spec:
      containers:
        - name: smilehelper-app
          image: gcr.io/smile-helper/smilehelper-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
      imagePullSecrets:
        - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: smilehelper-service
spec:
  type: LoadBalancer
  selector:
    app: smilehelper-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080