version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: facialFitDb
      MYSQL_ROOT_PASSWORD: jiny0609
      MYSQL_USER: root
      MYSQL_PASSWORD: jiny0609
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
